# This is a basic workflow to help you get started with Actions

name: cicdpathtest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    steps:
      - name: repo-name-${{ github.run_id }}
      - uses: actions/checkout@v3
#        with: 
#          path: "/home/daryn/cicdpathtest/"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -al

#   path: repo-name-${{ github.run_id }}-${{ github.run_number }}

#  - run: mv repo-name-${{ github.run_id }}-${{ github.run_number }} ../repo-name
